### ISSUE TITLE
Import portable rc.subr from NetBSD

### ISSUE THREAD

**Issue by RainbowHackerHorse** [PurLinux/Base#1]
Import portable rc.subr and convert to use GNU Make for inclusion in Base as extension to busybox init
http://cvsweb.netbsd.org/bsdweb.cgi/pkgsrc/pkgtools/rc.subr/#dirlist

**Comment by ghost** [comment]
gonna take a whack at this now

**Comment by ghost** [comment]
relevant reference:

https://wiki.netbsd.org/pkgsrc/how_to_use_pkgsrc_on_linux/ (meta doc, includes troubleshooting. we should have all prereqs in arch with the base-devel and multilib-devel metapackages, so shouuuldn't be an issue i think)

ftp://ftp.netbsd.org/pub/pkgsrc/current/pkgsrc/bootstrap/README.Linux is a refdoc on specific tweaks- if possible, we may want to set up a parallel make conf under arch. that keeps things clean and git-able.

http://www.netbsd.org/docs/pkgsrc/platforms.html#linux the goodies

**Comment by RainbowHackerHorse** [comment]
Closing as this has been superseded.
