### ISSUE TITLE
Release Checker completion

### ISSUE THREAD

**Issue by RainbowHackerHorse** [PurLinux/Base#11]
Complete release checker URL list with most up to date URLs prior to first build

**Comment by ghost** [comment]
6bbf3f1eb1d46ed3e963dabc77c395f2cf5ff12b has the updated source list... there's still a small bug in that when a new version is fetched, it doesn't update the source list- but the release checker's totally being revamped with a new version anyways (so i can implement things like flagging certain upstream urls) that would make this bug irrelevant.
