### ISSUE TITLE
Import Latest LibreSSL Release

### ISSUE THREAD

**Issue by RainbowHackerHorse** [PurLinux/Base#14]
We'll be shipping OpenBSD's LibreSSL library instead of OpenSSL.
Import that sucker.

**Comment by ghost** [comment]
added to contrib just tonight, but haven't incorporated into build yet

**Comment by alexfornuto** [comment]
> We'll be shipping OpenBSD's LibreSSL library instead of OpenSSL.

Why?

**Comment by RainbowHackerHorse** [comment]
@alexfornuto Due to OpenSSL's history of nasty CVE's, we're going with a more secure fork. LibreSSL is developed by the OpenBSD team, also responsible for software like OpenSSH.
We feel this is the best direction to go in, as the writers are focused on code correctness and security.

**Comment by ghost** [comment]
done. fingers crossed it doesn't cause issues down the road, but i guess we'll find out soon enough.
