### ISSUE TITLE
Add a screenshot on README 

### ISSUE THREAD

**Issue by ericoporto** [PurLinux/Base#22]
Add some screenshots directly on README so it's clear what is being shipped here.

**Comment by RainbowHackerHorse** [comment]
Sorry, screenshots of what? There's no GUI (unless you install one yourself from pkgsrc, and then I assume you know what it looks like). Should I put up a screenshot of the ever venerable command line?
If you use *NIX at all you know what it looks like already. No, there's no need for screenshots.

**Comment by ericoporto** [comment]
My workplace right now is terminator in Gentoo, with 4 panes: slap-editor on the big one, lynx, ncmcpp for controlling my mpd radio, and htop for monitoring my Ubuntu server. My monitor doesn't work for some reason on pure terminal, so I need to use xrandr (it's on autostart or somewhere else, it's been ages). Mainly this looks like a possible alternative to Gentoo. I can't tell.

**Comment by RainbowHackerHorse** [comment]
Well, we're not shipping Xorg or any GUI by default. So there's nothing to screencap. If you want to install from pkgsrc, you can always install whatever you want. 
http://pkgsrc.se/search.php?so=xrandr
http://pkgsrc.se/x11/py-terminator
http://pkgsrc.se/x11

Everything you need ships in the ports tree.

Re: alternative to gentoo: we're doing (in my opinion) what Gentoo failed to do. They brought the ports concept over, but they mangled it in their attempt to make it fit the "in linux everything is a package there's no base OS" paradigm.
Obviously i hold no animosity towards gentoo or their developers (one of the members of Core is in fact, a daily gentoo user).
However, we're not exactly an alternative. We're a whole different animal. We're doing something that hasn't really been done in Linuxland. There have been vaguely similar projects, but our implementation is new to peguiworld.
